sudo: required
dist: trusty
language: node_js
addons:
  chrome: stable
notifications:
  email:
    on_failure: always
    on_success: never
node_js:
- '8'
branches:
  only:
  - master
before_install:
- sudo apt-get install libavahi-compat-libdnssd-dev
script:
- npm test